ALTER TABLE PMOWN.TN_PM_SBD_OPER_PLCY ADD (
    SBD_STRT_HR NUMBER(2,0) DEFAULT 5 NOT NULL ENABLE VALIDATE,
    SBD_END_HR NUMBER(2,0) DEFAULT 1 NOT NULL ENABLE VALIDATE
);

ALTER TABLE PMOWN.TN_PM_SBD_OPER_PLCY ADD CONSTRAINT TN_PM_SBD_OPER_PLCY_CK1
    CHECK (
        SBD_STRT_HR >= 0
        AND SBD_END_HR >= 0
        AND SBD_STRT_HR >= SBD_END_HR
    );

COMMENT ON COLUMN PMOWN.TN_PM_SBD_OPER_PLCY.SBD_STRT_HR IS '자동수하물위탁개시시간';
COMMENT ON COLUMN PMOWN.TN_PM_SBD_OPER_PLCY.SBD_END_HR IS '자동수하물위탁종료시간';
