ALTER TABLE PMOWN.TN_PM_SLF_CHKN_OPER_PLCY ADD (
    PLCY_BGNG_YMD VARCHAR2(8),
    PLCY_END_YMD VARCHAR2(8)
);

MERGE INTO PMOWN.TN_PM_SLF_CHKN_OPER_PLCY T
USING (
    WITH ORDERED_POLICY AS (
        SELECT
            ROWID AS RID,
            TMNL_ID,
            SLF_CHKN_ISTR_ID,
            ALN_CD,
            PLCY_YMD,
            CASE
                WHEN LAG(PLCY_YMD) OVER (
                    PARTITION BY TMNL_ID, SLF_CHKN_ISTR_ID, ALN_CD
                    ORDER BY PLCY_YMD
                ) = TO_CHAR(TO_DATE(PLCY_YMD, 'YYYYMMDD') - 1, 'YYYYMMDD')
                THEN 0
                ELSE 1
            END AS NEW_PERIOD_YN
        FROM PMOWN.TN_PM_SLF_CHKN_OPER_PLCY
    ),
    GROUPED_POLICY AS (
        SELECT
            RID,
            TMNL_ID,
            SLF_CHKN_ISTR_ID,
            ALN_CD,
            PLCY_YMD,
            SUM(NEW_PERIOD_YN) OVER (
                PARTITION BY TMNL_ID, SLF_CHKN_ISTR_ID, ALN_CD
                ORDER BY PLCY_YMD
                ROWS UNBOUNDED PRECEDING
            ) AS PERIOD_NO
        FROM ORDERED_POLICY
    ),
    RANGED_POLICY AS (
        SELECT
            RID,
            MIN(PLCY_YMD) OVER (
                PARTITION BY TMNL_ID, SLF_CHKN_ISTR_ID, ALN_CD, PERIOD_NO
            ) AS PLCY_BGNG_YMD,
            CASE
                WHEN MAX(PLCY_YMD) OVER (
                    PARTITION BY TMNL_ID, SLF_CHKN_ISTR_ID, ALN_CD, PERIOD_NO
                ) = MAX(PLCY_YMD) OVER ()
                THEN '99991231'
                ELSE MAX(PLCY_YMD) OVER (
                    PARTITION BY TMNL_ID, SLF_CHKN_ISTR_ID, ALN_CD, PERIOD_NO
                )
            END AS PLCY_END_YMD
        FROM GROUPED_POLICY
    )
    SELECT RID, PLCY_BGNG_YMD, PLCY_END_YMD
    FROM RANGED_POLICY
) S
ON (T.ROWID = S.RID)
WHEN MATCHED THEN
    UPDATE SET
        T.PLCY_BGNG_YMD = S.PLCY_BGNG_YMD,
        T.PLCY_END_YMD = S.PLCY_END_YMD;

DELETE FROM PMOWN.TN_PM_SLF_CHKN_OPER_PLCY T
WHERE T.ROWID IN (
    SELECT RID
    FROM (
        SELECT
            ROWID AS RID,
            ROW_NUMBER() OVER (
                PARTITION BY TMNL_ID, SLF_CHKN_ISTR_ID, ALN_CD, PLCY_BGNG_YMD
                ORDER BY PLCY_YMD
            ) AS ROW_NO
        FROM PMOWN.TN_PM_SLF_CHKN_OPER_PLCY
    )
    WHERE ROW_NO > 1
);

ALTER TABLE PMOWN.TN_PM_SLF_CHKN_OPER_PLCY DROP CONSTRAINT TN_PM_SLF_CHKN_OPER_PLCY_PK;

DROP INDEX PMOWN.TN_PM_SLF_CHKN_OPER_PLCY_IX01;

ALTER TABLE PMOWN.TN_PM_SLF_CHKN_OPER_PLCY DROP COLUMN PLCY_YMD;

ALTER TABLE PMOWN.TN_PM_SLF_CHKN_OPER_PLCY MODIFY (
    PLCY_BGNG_YMD NOT NULL,
    PLCY_END_YMD NOT NULL
);

ALTER TABLE PMOWN.TN_PM_SLF_CHKN_OPER_PLCY ADD CONSTRAINT TN_PM_SLF_CHKN_OPER_PLCY_PK
    PRIMARY KEY (TMNL_ID, SLF_CHKN_ISTR_ID, ALN_CD, PLCY_BGNG_YMD);

ALTER TABLE PMOWN.TN_PM_SLF_CHKN_OPER_PLCY ADD CONSTRAINT TN_PM_SLF_CHKN_OPER_PLCY_CK1
    CHECK (PLCY_BGNG_YMD <= PLCY_END_YMD);

CREATE INDEX PMOWN.TN_PM_SLF_CHKN_OPER_PLCY_IX01
    ON PMOWN.TN_PM_SLF_CHKN_OPER_PLCY (PLCY_BGNG_YMD, PLCY_END_YMD);

COMMENT ON COLUMN PMOWN.TN_PM_SLF_CHKN_OPER_PLCY.PLCY_BGNG_YMD IS '정책시작연월일';
COMMENT ON COLUMN PMOWN.TN_PM_SLF_CHKN_OPER_PLCY.PLCY_END_YMD IS '정책종료연월일';
