CREATE TABLE PMOWN.TH_PM_SMLT_ATRB_APLY_SET_HSTRY
(
    APLY_SET_SN           NUMBER(10)   NOT NULL,
    SRC_FIX_ATRB_GROUP_ID VARCHAR2(8)  NOT NULL,
    TGT_FIX_ATRB_GROUP_ID VARCHAR2(8)  NOT NULL,
    APLY_ROW_CNT          NUMBER(8)    DEFAULT 0 NOT NULL,
    CNCL_YN               VARCHAR2(1)  DEFAULT 'N' NOT NULL,
    CNCL_DT               TIMESTAMP(6),
    CNCL_RGTR_ID          VARCHAR2(40),
    FRST_RGTR_ID          VARCHAR2(40),
    FRST_RGTR_IP_ADDR     VARCHAR2(23),
    FRST_REG_DT           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT TH_PM_SMLT_ATRB_APLY_SET_PK PRIMARY KEY (APLY_SET_SN),
    CONSTRAINT TH_PM_SMLT_ATRB_APLY_SET_CK1 CHECK (CNCL_YN IN ('Y', 'N'))
);

CREATE INDEX PMOWN.TH_PM_SMLT_ATRB_APLY_SET_IX1
    ON PMOWN.TH_PM_SMLT_ATRB_APLY_SET_HSTRY (TGT_FIX_ATRB_GROUP_ID, CNCL_YN, APLY_SET_SN DESC);

CREATE SEQUENCE PMOWN.SQ1_TN_PM_SMLT_ATRB_APLY_SET
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

ALTER TABLE PMOWN.TH_PM_SMLT_ATRB_APLY_HSTRY ADD (
    APLY_SET_SN NUMBER(10)
);

INSERT INTO PMOWN.TH_PM_SMLT_ATRB_APLY_SET_HSTRY (
    APLY_SET_SN,
    SRC_FIX_ATRB_GROUP_ID,
    TGT_FIX_ATRB_GROUP_ID,
    APLY_ROW_CNT,
    CNCL_YN,
    CNCL_DT,
    CNCL_RGTR_ID,
    FRST_RGTR_ID,
    FRST_RGTR_IP_ADDR,
    FRST_REG_DT
)
SELECT
    A.APLY_SN - 1000000000,
    A.SRC_FIX_ATRB_GROUP_ID,
    A.TGT_FIX_ATRB_GROUP_ID,
    A.APLY_ROW_CNT,
    A.CNCL_YN,
    A.CNCL_DT,
    A.CNCL_RGTR_ID,
    A.FRST_RGTR_ID,
    A.FRST_RGTR_IP_ADDR,
    A.FRST_REG_DT
FROM PMOWN.TH_PM_SMLT_ATRB_APLY_HSTRY A;

UPDATE PMOWN.TH_PM_SMLT_ATRB_APLY_HSTRY
SET APLY_SET_SN = APLY_SN - 1000000000;

ALTER TABLE PMOWN.TH_PM_SMLT_ATRB_APLY_HSTRY ADD CONSTRAINT TH_PM_SMLT_ATRB_APLY_HSTRY_FK2
    FOREIGN KEY (APLY_SET_SN) REFERENCES PMOWN.TH_PM_SMLT_ATRB_APLY_SET_HSTRY (APLY_SET_SN);

CREATE INDEX PMOWN.TH_PM_SMLT_ATRB_APLY_HSTRY_IX3
    ON PMOWN.TH_PM_SMLT_ATRB_APLY_HSTRY (APLY_SET_SN, APLY_SN);

COMMENT ON TABLE PMOWN.TH_PM_SMLT_ATRB_APLY_SET_HSTRY IS 'PM_시뮬레이션속성전체세트적용이력';
COMMENT ON COLUMN PMOWN.TH_PM_SMLT_ATRB_APLY_SET_HSTRY.APLY_SET_SN IS '적용세트일련번호';
COMMENT ON COLUMN PMOWN.TH_PM_SMLT_ATRB_APLY_HSTRY.SRC_FIX_ATRB_GROUP_ID IS '원본고정속성그룹아이디';
COMMENT ON COLUMN PMOWN.TH_PM_SMLT_ATRB_APLY_SET_HSTRY.TGT_FIX_ATRB_GROUP_ID IS '대상고정속성그룹아이디';
COMMENT ON COLUMN PMOWN.TH_PM_SMLT_ATRB_APLY_HSTRY.APLY_ROW_CNT IS '적용전체행수';
COMMENT ON COLUMN PMOWN.TH_PM_SMLT_ATRB_APLY_HSTRY.APLY_SET_SN IS '적용세트일련번호';

COMMIT;
