CREATE TABLE "PMOWN"."TN_PM_SLF_CHKN_OPER_PLCY"
(
    "TMNL_ID" VARCHAR2(4) NOT NULL ENABLE VALIDATE,
    "SLF_CHKN_ISTR_ID" VARCHAR2(10) NOT NULL ENABLE VALIDATE,
    "ALN_CD" VARCHAR2(3) NOT NULL ENABLE VALIDATE,
    "PLCY_YMD" VARCHAR2(8) NOT NULL ENABLE VALIDATE,
    "FRST_RGTR_ID" VARCHAR2(40),
    "FRST_RGTR_IP_ADDR" VARCHAR2(23),
    "FRST_REG_DT" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "LAST_MDFR_ID" VARCHAR2(40),
    "LAST_MDFR_IP_ADDR" VARCHAR2(23),
    "LAST_MDFCN_DT" TIMESTAMP(6),
    CONSTRAINT "TN_PM_SLF_CHKN_OPER_PLCY_PK"
        PRIMARY KEY ("TMNL_ID", "SLF_CHKN_ISTR_ID", "ALN_CD", "PLCY_YMD")
);

CREATE INDEX "PMOWN"."TN_PM_SLF_CHKN_OPER_PLCY_IX01"
    ON "PMOWN"."TN_PM_SLF_CHKN_OPER_PLCY" ("PLCY_YMD");

COMMENT ON TABLE "PMOWN"."TN_PM_SLF_CHKN_OPER_PLCY" IS 'PM_셀프체크인운영정책';
COMMENT ON COLUMN "PMOWN"."TN_PM_SLF_CHKN_OPER_PLCY"."TMNL_ID" IS '터미널아이디';
COMMENT ON COLUMN "PMOWN"."TN_PM_SLF_CHKN_OPER_PLCY"."SLF_CHKN_ISTR_ID" IS '셀프체크인기기아이디';
COMMENT ON COLUMN "PMOWN"."TN_PM_SLF_CHKN_OPER_PLCY"."ALN_CD" IS '항공사코드';
COMMENT ON COLUMN "PMOWN"."TN_PM_SLF_CHKN_OPER_PLCY"."PLCY_YMD" IS '정책일자';
COMMENT ON COLUMN "PMOWN"."TN_PM_SLF_CHKN_OPER_PLCY"."FRST_RGTR_ID" IS '최초등록자아이디';
COMMENT ON COLUMN "PMOWN"."TN_PM_SLF_CHKN_OPER_PLCY"."FRST_RGTR_IP_ADDR" IS '최초등록자IP주소';
COMMENT ON COLUMN "PMOWN"."TN_PM_SLF_CHKN_OPER_PLCY"."FRST_REG_DT" IS '최초등록일시';
COMMENT ON COLUMN "PMOWN"."TN_PM_SLF_CHKN_OPER_PLCY"."LAST_MDFR_ID" IS '최종수정자아이디';
COMMENT ON COLUMN "PMOWN"."TN_PM_SLF_CHKN_OPER_PLCY"."LAST_MDFR_IP_ADDR" IS '최종수정자IP주소';
COMMENT ON COLUMN "PMOWN"."TN_PM_SLF_CHKN_OPER_PLCY"."LAST_MDFCN_DT" IS '최종수정일시';
