-- 출국심사 월별 국적별 자동/전체 인원 조회
SELECT
    YM,
    DOMPL_NOPE as KOR_TOTAL,
    DOMPL_AUTO_SRNG_NOPE as KOR_AUTO,
    FRCNY_NOPE as FOREIGN_TOTAL,
    FRCNY_AUTO_SRNG_NOPE as FOREIGN_AUTO
FROM PMOWN.TS_PM_MTLY_ENTCNY_DPTCNY_SRNG_NOPE
ORDER BY YM
