-- 운항편별 BSM 수하물 갯수
SELECT
	OUTFLTDATE as BSM_YMD,
	OUTFLTNUM as DDLN_FLTNM,
	FLTSH_ID,
	SEATNUM,
	ROW_NUMBER() OVER (PARTITION BY FLTSH_ID ORDER BY SEATNUM) as PASSENGER_SEQ,
	COUNT(*) as BSM_BAG_CNT
FROM PMOWN.DROP_AA_ESB_AIRBRS_BSM_RCV
WHERE FLTSH_ID IN ({placeholders})
GROUP BY OUTFLTDATE, OUTFLTNUM, FLTSH_ID, SEATNUM
ORDER BY BSM_YMD, DDLN_FLTNM, FLTSH_ID, PASSENGER_SEQ
