-- 출국장 개별 승객 태깅 시간 조회
SELECT
    FLTSH_ID,
    CHKN_SN,
    ALN_CD || FLTNM AS DDLN_FLTNM,
    DPTGT_ETRY_YMD  AS YMD,
    DPTGT_ETRY_HM  AS HM,
    CASE
        WHEN TMNL_SE_CD IN ('P01', 'P02')
        THEN 'T1'
        ELSE 'T2'
    END AS TMNL_ID,
    SUBSTR(TRNST_ISTR_ID, -5, 1) AS DG_NUMBER,
    TRNST_ISTR_ID,
    NTNLTY_CD,
    DPTGT_ETRY_CD
FROM PMOWN.TN_PM_PSG_SHOW_INFO
WHERE FLTSH_ID IN ({placeholders})
ORDER BY DDLN_FLTNM, HM
