-- 보딩게이트 개별 승객 태깅 시간 조회
SELECT
    FLTSH_ID,
    CHKN_SN,
    ALN_CD || FLTNM AS DDLN_FLTNM,
    BDPS_ISSU_YMD AS YMD,
    BDPS_ISSU_HR AS HM
FROM PMOWN.TN_PM_BDPS_ISSU_INFO
WHERE CHKN_SE_CD IN ('BG')
AND FLTSH_ID IN ({placeholders})
ORDER BY DDLN_FLTNM, HM