CREATE TABLE "PMOWN"."TN_PM_SCSH_OPER_PLCY"
(
    "OPER_YMD" VARCHAR2(8) NOT NULL ENABLE VALIDATE,
    "OPER_HOUR" NUMBER(2,0) NOT NULL ENABLE VALIDATE,
    "TMNL_ID" VARCHAR2(4) NOT NULL ENABLE VALIDATE,
    "DPTGT_NO" VARCHAR2(2) NOT NULL ENABLE VALIDATE,
    "SCSH_OPER_CNTOM" NUMBER(3,0) NOT NULL ENABLE VALIDATE,
    "FRST_RGTR_ID" VARCHAR2(40),
    "FRST_RGTR_IP_ADDR" VARCHAR2(23),
    "FRST_REG_DT" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "LAST_MDFR_ID" VARCHAR2(40),
    "LAST_MDFR_IP_ADDR" VARCHAR2(23),
    "LAST_MDFCN_DT" TIMESTAMP(6),
    CONSTRAINT "TN_PM_SCSH_OPER_PLCY_PK" PRIMARY KEY ("OPER_YMD", "OPER_HOUR", "TMNL_ID", "DPTGT_NO")
    USING INDEX
    PCTFREE 10 INITRANS 2 LOGGING
    TABLESPACE "TSIPM01" ENABLE VALIDATE
)
PCTFREE 10 INITRANS 2 NOCOMPRESS LOGGING
TABLESPACE "TSDPM01";

COMMENT ON TABLE "PMOWN"."TN_PM_SCSH_OPER_PLCY" IS 'PM_보안검색운영정책';
COMMENT ON COLUMN "PMOWN"."TN_PM_SCSH_OPER_PLCY"."OPER_YMD" IS '운영일자';
COMMENT ON COLUMN "PMOWN"."TN_PM_SCSH_OPER_PLCY"."OPER_HOUR" IS '운영시간';
COMMENT ON COLUMN "PMOWN"."TN_PM_SCSH_OPER_PLCY"."TMNL_ID" IS '터미널아이디';
COMMENT ON COLUMN "PMOWN"."TN_PM_SCSH_OPER_PLCY"."DPTGT_NO" IS '출국장번호';
COMMENT ON COLUMN "PMOWN"."TN_PM_SCSH_OPER_PLCY"."SCSH_OPER_CNTOM" IS '보안검색운영대수';
COMMENT ON COLUMN "PMOWN"."TN_PM_SCSH_OPER_PLCY"."FRST_RGTR_ID" IS '최초등록자아이디';
COMMENT ON COLUMN "PMOWN"."TN_PM_SCSH_OPER_PLCY"."FRST_RGTR_IP_ADDR" IS '최초등록자IP주소';
COMMENT ON COLUMN "PMOWN"."TN_PM_SCSH_OPER_PLCY"."FRST_REG_DT" IS '최초등록일시';
COMMENT ON COLUMN "PMOWN"."TN_PM_SCSH_OPER_PLCY"."LAST_MDFR_ID" IS '최종수정자아이디';
COMMENT ON COLUMN "PMOWN"."TN_PM_SCSH_OPER_PLCY"."LAST_MDFR_IP_ADDR" IS '최종수정자IP주소';
COMMENT ON COLUMN "PMOWN"."TN_PM_SCSH_OPER_PLCY"."LAST_MDFCN_DT" IS '최종수정일시';
